### ISSUE TITLE
PDF & PNG versions of key schematics and part assemblies?

### ISSUE THREAD

**Issue by ghost** [OpenAgInitiative/openag_eagle#1]
Please excuse my early enthusiasm--I know this project hasn't been announced formally yet, the readme says it's a work in progress, etc. Caleb's snapshots on instagram look really good, and I'm intrigued. It looks like the first one was a nervous system board and I'm guessing the second one was a PFC EDU v1.0 prototype.

I don't know what your documentation plan is, but from my perspective as a developer, it would be great to have .pdf, .png, or .txt versions of at least a few key files so that it's possible to study the design without having to license proprietary CAD tools.

At the top of my wish list:

1. PDF schematics for whatever you consider to be the key designs from
    - https://github.com/OpenAgInitiative/openag_eagle/tree/master/proj/PFC_EDU/V1.0/Electrical
    - https://github.com/OpenAgInitiative/openag_eagle/tree/master/proj/nervous-system/v2.0
    - https://github.com/OpenAgInitiative/openag_eagle/tree/master/proj/light-controller/v2.1
    - https://github.com/OpenAgInitiative/openag_eagle/tree/master/proj/sensor-nodes.

   I primarily care about GPIO pin maps for BeagleBone & Photon, plus part numbers for tracking down datasheets.

2. A PNG screenshot or two showing the overall assembly for the contents of https://github.com/OpenAgInitiative/openag_eagle/tree/master/proj/PFC_EDU/V1.0/Mechanical

**Comment by rbaynes** [comment]
@wsnook you will just have to wait and give us time to get everything "done".   We are a very small team and 100% focused on building now, hence not much chatter on the forum.    Feel free to look at what is public.

**Comment by ghost** [comment]
@rbaynes I'm sorry if it wasn't more clear from my description, but here is my rationale for this request:

1. I know you have limited resources for software development, and I am potentially interested in helping you--for free.

2. In order to help you, I would need information that's locked in a proprietary file format.

3. My expectation is that it would take someone with an Eagle and SolidWorks license less than 15 minutes to generate what I've asked for--probably like 5 minutes. This type of documentation is what enables participation from the Open Source developer community, so it's a good investment.

4. I'm not asking for a Q&A session or extensive documentation. Just the schematics.

**Comment by ghost** [comment]
@rbaynes Actually, never mind. It turns out that the board size limitation on the free version of EAGLE doesn't apply to schematics. I thought that would prevent me from generating PDFs on my own, but I was wrong.

In my fork of this repo, I'm currently in the process of exporting pdf schematics for all your .sch files. I could make a pull request if you're willing to accept one.

**Comment by jakerye** [comment]
@wsnook Thanks for the great feedback. Once stable, documentation will include pdfs/pngs of the schematic & board files along with a BOM and manufacturing (gerber) files. I've been working on an eagle script and part attribution convention to make this sort of documentation trivial to generate in a format that is easily viewable on github. I'm excited to see your enthusiasm! I just don't want to jump the gun before we have a minimally stable system, but it is close! Once initial documentation is out, It'd be great to get more of your feedback / ideas on it.

**Comment by ghost** [comment]
@jakerye Okay, awesome. Sounds like it will probably work better for you guys if I just keep what I'm doing in my own branch for now and keep an eye out for your new commits.

**Comment by ghost** [comment]
@jakerye I went through all your boards and schematics. Great stuff! I particularly like what you did with the PCA9615 differential I2C buffers and the T6713.

FWIW, I'd suggest adding some provision for battery-backed RTC. Even a cheap, low-precision clock could be a lot better than nothing for schools with marginal networks. The only thing that's caused me any real grief with my Raspberry Pi & Photon data logging in the last year has been NTP-related glitches when my system is coming back up after a power or network outage.

**Comment by jakerye** [comment]
@wsnook I agree with the RTC and anticipate one being in the nvs v2.1 and pfc-edu v1.1. When we put the v1.0 pfc in a few boston schools a while back, we saw a wide variance in school wifi reliability. For the next round of systems they will be able to run reliably without a network connection and have extra features when it is present.

**Comment by Poitrast** [comment]
@wsnook, I appreciate the feedback as well!  Before you go too far down the
rabbit hole on moving forward with the prototype schematics I have to warn
you they are alpha stage development, and are very much subject to
change/incomplete in some cases.  It may be premature to even fork these
designs at the moment.  With that being said, we are always open to
contstructive feedback/considerations.

Thanks,

Dan

**Comment by ghost** [comment]
@Poitrast No worries. I'm used to working iteratively and reversing stuff without much to go on. I can tell from things like the 3.3V supply & BBB/Photon wiring on the nervous system board that you're not done yet.

Mostly I'm just trying to get a sense of whether there's enough structure that I might be able to start prototyping code that could potentially be relevant and helpful down the road. My sense is that it might be reasonable to start playing with code for accessing I2C sensors and actuators from linux userspace through an [Adafruit TCA9548A I2C mux](https://learn.adafruit.com/adafruit-tca9548a-1-to-8-i2c-multiplexer-breakout/overview) breakout board.

From what you've done so far, I can get a sense of the I2C bus topologies that might be possible. That's helpful.

**Comment by ghost** [comment]
@jakerye The READMEs and PNGs you've added recently are excellent for better understanding your designs and the intent behind them. From my perspective at least, that level of detail is more than sufficient. Thanks!
